const SENATE_DATA = {
  2024: {
    title: "2024 Senate Elections",
    results: {
      "Alabama": { party: "R", winner: "Tommy Tuberville", pct: 66.6 },
      "Alaska": { party: "R", winner: "Lisa Murkowski", pct: 53.7 },
      "Arizona": { party: "D", winner: "Ruben Gallego", pct: 51.0 },
      "California": { party: "D", winner: "Adam Schiff", pct: 56.3 },
      "Connecticut": { party: "D", winner: "Chris Murphy", pct: 60.8 },
      "Delaware": { party: "D", winner: "Lisa Blunt Rochester", pct: 56.2 },
      "Florida": { party: "R", winner: "Rick Scott", pct: 56.5 },
      "Georgia": { party: "R", winner: "Jon Ossoff", pct: 48.5, note: "runoff" },
      "Hawaii": { party: "D", winner: "Brian Schatz", pct: 71.6 },
      "Idaho": { party: "R", winner: "Mike Simpson", pct: 65.1 },
      "Illinois": { party: "D", winner: "Dick Durbin", pct: 57.3 },
      "Indiana": { party: "R", winner: "Mike Braun", pct: 56.5 },
      "Iowa": { party: "R", winner: "Joni Ernst", pct: 56.8 },
      "Kansas": { party: "R", winner: "Jerry Moran", pct: 67.9 },
      "Kentucky": { party: "R", winner: "Mitch McConnell", pct: 57.8 },
      "Louisiana": { party: "R", winner: "Bill Cassidy", pct: 54.4 },
      "Maine": { party: "D", winner: "Angus King", pct: 54.6 },
      "Maryland": { party: "D", winner: "Angela Alsobrooks", pct: 52.4 },
      "Massachusetts": { party: "D", winner: "Elizabeth Warren", pct: 64.2 },
      "Michigan": { party: "D", winner: "Elissa Slotkin", pct: 48.7 },
      "Minnesota": { party: "D", winner: "Amy Klobuchar", pct: 58.6 },
      "Mississippi": { party: "R", winner: "Roger Wicker", pct: 64.2 },
      "Missouri": { party: "R", winner: "Josh Hawley", pct: 55.7 },
      "Montana": { party: "R", winner: "Tim Sheehy", pct: 53.4 },
      "Nebraska": { party: "R", winner: "Deb Fischer", pct: 61.3 },
      "Nevada": { party: "D", winner: "Jacky Rosen", pct: 50.3 },
      "New Hampshire": { party: "D", winner: "Jeanne Shaheen", pct: 53.6 },
      "New Jersey": { party: "D", winner: "Andy Kim", pct: 52.2 },
      "New Mexico": { party: "D", winner: "Martin Heinrich", pct: 58.4 },
      "New York": { party: "D", winner: "Kirsten Gillibrand", pct: 58.7 },
      "North Dakota": { party: "R", winner: "Kevin Cramer", pct: 65.6 },
      "Ohio": { party: "R", winner: "Bernie Moreno", pct: 50.0 },
      "Pennsylvania": { party: "D", winner: "Bob Casey", pct: 48.8 },
      "Rhode Island": { party: "D", winner: "Sheldon Whitehouse", pct: 60.0 },
      "Tennessee": { party: "R", winner: "Marsha Blackburn", pct: 65.1 },
      "Texas": { party: "R", winner: "Ted Cruz", pct: 53.2 },
      "Utah": { party: "R", winner: "John Curtis", pct: 55.7 },
      "Vermont": { party: "D", winner: "Bernie Sanders", pct: 64.3 },
      "Virginia": { party: "D", winner: "Tim Kaine", pct: 55.5 },
      "Washington": { party: "D", winner: "Maria Cantwell", pct: 59.4 },
      "West Virginia": { party: "R", winner: "Jim Justice", pct: 65.6 },
      "Wisconsin": { party: "D", winner: "Tammy Baldwin", pct: 48.9 },
      "Wyoming": { party: "R", winner: "John Barrasso", pct: 73.0 }
    }
  },
  2022: {
    title: "2022 Senate Elections",
    results: {
      "Alabama": { party: "R", winner: "Katie Boyd Britt", pct: 66.6 },
      "Alaska": { party: "R", winner: "Lisa Murkowski", pct: 53.7 },
      "Arizona": { party: "D", winner: "Mark Kelly", pct: 51.4 },
      "Arkansas": { party: "R", winner: "John Boozman", pct: 65.8 },
      "California": { party: "D", winner: "Alex Padilla", pct: 59.2 },
      "Colorado": { party: "D", winner: "Michael Bennet", pct: 55.9 },
      "Connecticut": { party: "D", winner: "Richard Blumenthal", pct: 59.1 },
      "Florida": { party: "R", winner: "Marco Rubio", pct: 57.7 },
      "Georgia": { party: "D", winner: "Raphael Warnock", pct: 51.4 },
      "Hawaii": { party: "D", winner: "Brian Schatz", pct: 71.4 },
      "Idaho": { party: "R", winner: "Mike Crapo", pct: 66.5 },
      "Illinois": { party: "D", winner: "Tammy Duckworth", pct: 56.0 },
      "Indiana": { party: "R", winner: "Todd Young", pct: 59.4 },
      "Iowa": { party: "R", winner: "Chuck Grassley", pct: 55.6 },
      "Kansas": { party: "R", winner: "Jerry Moran", pct: 59.8 },
      "Kentucky": { party: "R", winner: "Rand Paul", pct: 61.8 },
      "Louisiana": { party: "R", winner: "John Kennedy", pct: 63.9 },
      "Maryland": { party: "D", winner: "Chris Van Hollen", pct: 56.3 },
      "Missouri": { party: "R", winner: "Eric Schmitt", pct: 55.7 },
      "Nevada": { party: "D", winner: "Catherine Cortez Masto", pct: 48.8 },
      "New Hampshire": { party: "D", winner: "Maggie Hassan", pct: 53.6 },
      "New York": { party: "D", winner: "Chuck Schumer", pct: 55.8 },
      "North Carolina": { party: "R", winner: "Ted Budd", pct: 50.7 },
      "North Dakota": { party: "R", winner: "John Hoeven", pct: 69.3 },
      "Ohio": { party: "R", winner: "JD Vance", pct: 53.3 },
      "Oklahoma": { party: "R", winner: "James Lankford", pct: 64.7 },
      "Oregon": { party: "D", winner: "Ron Wyden", pct: 56.0 },
      "Pennsylvania": { party: "D", winner: "John Fetterman", pct: 51.3 },
      "South Carolina": { party: "R", winner: "Tim Scott", pct: 63.1 },
      "South Dakota": { party: "R", winner: "John Thune", pct: 65.9 },
      "Utah": { party: "R", winner: "Mike Lee", pct: 53.2 },
      "Vermont": { party: "D", winner: "Peter Welch", pct: 68.4 },
      "Washington": { party: "D", winner: "Patty Murray", pct: 57.2 },
      "Wisconsin": { party: "D", winner: "Ron Johnson", pct: 50.5 }
    }
  },
  2020: {
    title: "2020 Senate Elections",
    results: {
      "Alabama": { party: "R", winner: "Tommy Tuberville", pct: 67.7 },
      "Alaska": { party: "R", winner: "Dan Sullivan", pct: 53.8 },
      "Arizona": { party: "D", winner: "Mark Kelly", pct: 51.2 },
      "Arkansas": { party: "R", winner: "Tom Cotton", pct: 66.5 },
      "Colorado": { party: "D", winner: "John Hickenlooper", pct: 53.5 },
      "Delaware": { party: "D", winner: "Chris Coons", pct: 62.5 },
      "Georgia": { party: "D", winner: "Jon Ossoff", pct: 50.6 },
      "Georgia (special)": { party: "D", winner: "Raphael Warnock", pct: 51.0 },
      "Idaho": { party: "R", winner: "Jim Risch", pct: 62.6 },
      "Illinois": { party: "D", winner: "Dick Durbin", pct: 53.8 },
      "Iowa": { party: "R", winner: "Joni Ernst", pct: 51.8 },
      "Kansas": { party: "R", winner: "Roger Marshall", pct: 53.3 },
      "Kentucky": { party: "R", winner: "Mitch McConnell", pct: 57.8 },
      "Louisiana": { party: "R", winner: "Bill Cassidy", pct: 59.4 },
      "Maine": { party: "D", winner: "Sara Gideon", pct: 42.4, note: "lost" },
      "Michigan": { party: "D", winner: "Gary Peters", pct: 49.9 },
      "Minnesota": { party: "D", winner: "Tina Smith", pct: 48.8 },
      "Mississippi": { party: "R", winner: "Cindy Hyde-Smith", pct: 54.2 },
      "Montana": { party: "R", winner: "Steve Daines", pct: 54.9 },
      "Nebraska": { party: "R", winner: "Ben Sasse", pct: 62.9 },
      "New Hampshire": { party: "D", winner: "Jeanne Shaheen", pct: 56.8 },
      "New Jersey": { party: "D", winner: "Cory Booker", pct: 57.3 },
      "New Mexico": { party: "D", winner: "Ben Ray Luján", pct: 51.7 },
      "North Carolina": { party: "R", winner: "Thom Tillis", pct: 48.7 },
      "Oklahoma": { party: "R", winner: "Jim Inhofe", pct: 67.4 },
      "Oregon": { party: "D", winner: "Jeff Merkley", pct: 56.8 },
      "Rhode Island": { party: "D", winner: "Jack Reed", pct: 67.2 },
      "South Carolina": { party: "R", winner: "Lindsey Graham", pct: 54.5 },
      "South Dakota": { party: "R", winner: "Mike Rounds", pct: 65.4 },
      "Tennessee": { party: "R", winner: "Bill Hagerty", pct: 62.2 },
      "Texas": { party: "R", winner: "John Cornyn", pct: 53.5 },
      "Virginia": { party: "D", winner: "Mark Warner", pct: 56.2 },
      "West Virginia": { party: "R", winner: "Shelley Moore Capito", pct: 65.3 },
      "Wyoming": { party: "R", winner: "Cynthia Lummis", pct: 73.3 }
    }
  },
  2018: {
    title: "2018 Senate Elections",
    results: {
      "Arizona": { party: "D", winner: "Kyrsten Sinema", pct: 50.3 },
      "California": { party: "D", winner: "Dianne Feinstein", pct: 54.0 },
      "Connecticut": { party: "D", winner: "Chris Murphy", pct: 59.7 },
      "Delaware": { party: "D", winner: "Tom Carper", pct: 59.6 },
      "Florida": { party: "R", winner: "Rick Scott", pct: 50.1 },
      "Georgia": { party: "R", winner: "David Perdue", pct: 52.3 },
      "Hawaii": { party: "D", winner: "Mazie Hirono", pct: 71.2 },
      "Indiana": { party: "R", winner: "Mike Braun", pct: 51.1 },
      "Maine": { party: "R", winner: "Susan Collins", pct: 54.0 },
      "Maryland": { party: "D", winner: "Ben Cardin", pct: 65.4 },
      "Massachusetts": { party: "D", winner: "Elizabeth Warren", pct: 60.3 },
      "Michigan": { party: "D", winner: "Debbie Stabenow", pct: 52.3 },
      "Minnesota": { party: "D", winner: "Amy Klobuchar", pct: 60.3 },
      "Mississippi": { party: "R", winner: "Roger Wicker", pct: 58.5 },
      "Missouri": { party: "R", winner: "Josh Hawley", pct: 51.4 },
      "Montana": { party: "D", winner: "Jon Tester", pct: 50.3 },
      "Nebraska": { party: "R", winner: "Deb Fischer", pct: 58.4 },
      "Nevada": { party: "D", winner: "Jacky Rosen", pct: 50.4 },
      "New Jersey": { party: "D", winner: "Bob Menendez", pct: 53.6 },
      "New Mexico": { party: "D", winner: "Martin Heinrich", pct: 54.0 },
      "New York": { party: "D", winner: "Kirsten Gillibrand", pct: 67.1 },
      "North Dakota": { party: "R", winner: "Kevin Cramer", pct: 54.9 },
      "Ohio": { party: "D", winner: "Sherrod Brown", pct: 53.4 },
      "Pennsylvania": { party: "D", winner: "Bob Casey", pct: 55.7 },
      "Rhode Island": { party: "D", winner: "Sheldon Whitehouse", pct: 61.0 },
      "Tennessee": { party: "R", winner: "Marsha Blackburn", pct: 54.7 },
      "Texas": { party: "R", winner: "Ted Cruz", pct: 50.9 },
      "Utah": { party: "R", winner: "Mitt Romney", pct: 62.6 },
      "Vermont": { party: "D", winner: "Bernie Sanders", pct: 67.4 },
      "Virginia": { party: "D", winner: "Tim Kaine", pct: 57.0 },
      "Washington": { party: "D", winner: "Maria Cantwell", pct: 58.6 },
      "West Virginia": { party: "D", winner: "Joe Manchin", pct: 49.6 },
      "Wisconsin": { party: "D", winner: "Tammy Baldwin", pct: 55.4 },
      "Wyoming": { party: "R", winner: "John Barrasso", pct: 67.1 }
    }
  },
  2016: {
    title: "2016 Senate Elections",
    results: {
      "Alabama": { party: "R", winner: "Richard Shelby", pct: 63.9 },
      "Alaska": { party: "R", winner: "Lisa Murkowski", pct: 52.5 },
      "Arizona": { party: "R", winner: "John McCain", pct: 53.7 },
      "Arkansas": { party: "R", winner: "John Boozman", pct: 65.9 },
      "California": { party: "D", winner: "Kamala Harris", pct: 61.6 },
      "Colorado": { party: "D", winner: "Michael Bennet", pct: 50.0 },
      "Connecticut": { party: "D", winner: "Richard Blumenthal", pct: 62.9 },
      "Florida": { party: "R", winner: "Marco Rubio", pct: 52.0 },
      "Georgia": { party: "R", winner: "Johnny Isakson", pct: 54.8 },
      "Hawaii": { party: "D", winner: "Brian Schatz", pct: 73.6 },
      "Idaho": { party: "R", winner: "Mike Crapo", pct: 66.7 },
      "Illinois": { party: "D", winner: "Tammy Duckworth", pct: 53.0 },
      "Indiana": { party: "R", winner: "Todd Young", pct: 52.1 },
      "Iowa": { party: "R", winner: "Chuck Grassley", pct: 60.2 },
      "Kansas": { party: "R", winner: "Jerry Moran", pct: 62.2 },
      "Kentucky": { party: "R", winner: "Rand Paul", pct: 57.3 },
      "Louisiana": { party: "R", winner: "John Kennedy", pct: 61.0 },
      "Maryland": { party: "D", winner: "Chris Van Hollen", pct: 60.2 },
      "Missouri": { party: "R", winner: "Roy Blunt", pct: 49.2 },
      "Nevada": { party: "D", winner: "Catherine Cortez Masto", pct: 47.1 },
      "New Hampshire": { party: "D", winner: "Maggie Hassan", pct: 47.6 },
      "New York": { party: "D", winner: "Chuck Schumer", pct: 70.4 },
      "North Carolina": { party: "R", winner: "Richard Burr", pct: 51.1 },
      "North Dakota": { party: "R", winner: "John Hoeven", pct: 78.5 },
      "Ohio": { party: "R", winner: "Rob Portman", pct: 58.0 },
      "Oklahoma": { party: "R", winner: "James Lankford", pct: 67.8 },
      "Oregon": { party: "D", winner: "Ron Wyden", pct: 56.6 },
      "Pennsylvania": { party: "R", winner: "Pat Toomey", pct: 48.8 },
      "South Carolina": { party: "R", winner: "Tim Scott", pct: 60.6 },
      "South Dakota": { party: "R", winner: "John Thune", pct: 71.8 },
      "Utah": { party: "R", winner: "Mike Lee", pct: 68.1 },
      "Vermont": { party: "D", winner: "Patrick Leahy", pct: 61.3 },
      "Washington": { party: "D", winner: "Patty Murray", pct: 58.8 },
      "Wisconsin": { party: "R", winner: "Ron Johnson", pct: 50.2 }
    }
  }
};
